//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOnkyo.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOnkyo.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 26
        ///01 00 00 00 
        ///21 31 45 43 
        ///4e 54 58 2d 
        ///4e 52 35 30 
        ///39 2f 36 30 
        ///31 32 38 2f 
        ///58 58 2f 30 
        ///30 30 39 42 
        ///30 43 30 45 
        ///38 43 33 19 
        ///0d 0a 00 00
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0b
        ///01 00 00 00 
        ///21 31 4e 4c 
        ///53 43 2d 50 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 13 01
        ///00 00 00 21 
        ///31 4e 54 4d 
        ///36 37 3a 32 
        ///36 2f 2d 2d 
        ///3a 2d 2d 1a
        ///0d 0a 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DoubleMessage {
            get {
                return ResourceManager.GetString("DoubleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0b 
        ///01 00 00 00 
        ///21 31 4e 4c 
        ///53 43 30 50 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 10 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 30 2d 31 
        ///4c 49 56 45 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 10 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 31 2d 42 
        ///69 67 46 4d 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 14 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 32 2d 42 
        ///61 73 73 44 
        ///72 69 76 65 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 13 01 
        ///00 00 00 21 
        ///31 4e 4c [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MessageBuffer1 {
            get {
                return ResourceManager.GetString("MessageBuffer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 31 4e 4c 53 
        ///55 36 2d 4c 
        ///61 75 74 2e 
        ///66 6d 20 2f 
        ///4d 61 67 69 
        ///63 20 6f 66 
        ///20 4d 75 73 
        ///69 63 1a 0d 
        ///0a 49 53 43 
        ///50 00 00 00 
        ///10 00 00 00 
        ///29 01 00 00 
        ///00 21 31 4e 
        ///4c 53 55 37 
        ///2d 4c 61 75 
        ///74 2e 66 6d 
        ///20 2f 20 52 
        ///6f 63 6b 20 
        ///74 68 65 20 
        ///66 75 6e 6b 
        ///79 20 62 65 
        ///61 74 7a 1a 
        ///0d 0a 49 53 
        ///43 50 00 00 
        ///00 10 00 00 
        ///00 16 01 00 
        ///00 00 21 31 
        ///4e 4c 53 55 
        ///38 2d 44 65 
        ///6c 74 61 20 
        ///52 61 64 69 
        ///6f 1a 0d 0a 
        ///49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 16 
        ///01 00 00 00 
        ///21 31 4e [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MessageBuffer2 {
            get {
                return ResourceManager.GetString("MessageBuffer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die !1NJA00424D36040100000000003604000028000000800000008000000001000800000000000000000000000000000000000001000000010000B3B2B4FFACABADFFA2A1A3FFD3D3D3FF9B9A9CFFACACACFF3E3E3EFF989898FF818181FFA0A0A0FF908F90FF969597FF454545FFA3A2A4FF959596FF878787FF2F2F2FFFCA 
        ///!1NJA01CACAFFCCCCCCFFA9A8AAFF3A3A3AFF9E9D9FFFA7A7A8FFA1A0A2FFB8B7B8FF737373FFA5A4A5FFA4A3A5FFE0E0E0FF606060FFBBBABBFF858485FFD7D7D7FFE4E4E4FFC6C6C6FFB1B0B2FF838383FF9E9D9FFF707070FF383838FF787878FFDADADAFF656565FF6D6D6DFF868686FFB5B4B5FF636363FF9B9B9CFF 
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string NetJacketArt {
            get {
                return ResourceManager.GetString("NetJacketArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0b 
        ///01 00 00 00 
        ///21 31 4e 4c 
        ///53 43 38 50 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 1a 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 30 2d 46 
        ///61 6d 69 6c 
        ///79 20 50 6f 
        ///72 74 72 61 
        ///69 74 1a 0d 
        ///0a 49 53 43 
        ///50 00 00 00 
        ///10 00 00 00 
        ///2d 01 00 00 
        ///00 21 31 4e 
        ///4c 53 55 31 
        ///2d 46 75 6e 
        ///68 6f 75 73 
        ///65 20 28 4d 
        ///61 69 6e 20 
        ///56 65 72 73 
        ///69 6f 6e 29 
        ///20 5b 45 78 
        ///70 6c 69 63 
        ///69 74 5d 1a 
        ///0d 0a 49 53 
        ///43 50 00 00 
        ///00 10 00 00 
        ///00 2e 01 00 
        ///00 00 21 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string NetList1 {
            get {
                return ResourceManager.GetString("NetList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 72 6f 75 62 
        ///6c 65 1a 0d 
        ///0a 49 53 43 
        ///50 00 00 00 
        ///10 00 00 00 
        ///22 01 00 00 
        ///00 21 31 4e 
        ///4c 53 55 35 
        ///2d 57 68 6f 
        ///20 4b 6e 65 
        ///77 20 28 4d 
        ///61 69 6e 20 
        ///56 65 72 73 
        ///69 6f 6e 29 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 27 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 36 2d 42 
        ///61 64 20 49 
        ///6e 66 6c 75 
        ///65 6e 63 65 
        ///20 28 4d 61 
        ///69 6e 20 56 
        ///65 72 73 69 
        ///6f 6e 29 1a 
        ///0d 0a 49 53 
        ///43 50 00 00 
        ///00 10 00 00 
        ///00 43 01 00 
        ///00 00 21 31 
        ///4e 4c 53 55 
        ///37 2d 44 65 
        ///61 72 20 4d 
        ///72 2e 20 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string NetList2 {
            get {
                return ResourceManager.GetString("NetList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 69 6f 20 45 
        ///64 69 74 29 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 2d 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 39 2d 46 
        ///2a 2a 6b 69 
        ///6e 27 20 50 
        ///65 72 66 65 
        ///63 74 20 28 
        ///45 78 70 6c 
        ///69 63 69 74 
        ///20 56 65 72 
        ///73 69 6f 6e 
        ///29 1a 0d 0a 
        ///49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0a 
        ///01 00 00 00 
        ///21 31 41 4d 
        ///54 30 30 1a 
        ///0d 0a 49 53 
        ///43 50 00 00 
        ///00 10 00 00 
        ///00 0a 01 00 
        ///00 00 21 31 
        ///4c 4d 44 30 
        ///43 1a 0d 0a 
        ///49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0a 
        ///01 00 00 00 
        ///21 31 4d 56 
        ///4c 30 46 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string NetList3 {
            get {
                return ResourceManager.GetString("NetList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 1e
        ///01 00 00 00 
        ///21 31 4e 4c 
        ///54 30 31 32 
        ///32 30 30 30 
        ///30 30 30 30 
        ///30 30 30 30 
        ///30 30 30 30 
        ///31 30 30 1a 
        ///0d 0a 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00 00 
        ///00 00 00  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SingleMessage {
            get {
                return ResourceManager.GetString("SingleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 49 53 43 50 
        ///00 00 00 10 
        ///00 00 00 0b 
        ///01 00 00 00 
        ///21 31 4e 4c 
        ///53 43 30 50 
        ///1a 0d 0a 49 
        ///53 43 50 00 
        ///00 00 10 00 
        ///00 00 1b 01 
        ///00 00 00 21 
        ///31 4e 4c 53 
        ///55 30 2d 48 
        ///c3 a4 75 66 
        ///69 67 20 67 
        ///65 73 70 69 
        ///65 6c 74 1a 
        ///0d 0a 49 53 
        ///43 50 00 00 
        ///00 10 00 00 
        ///00 1b 01 00 
        ///00 00 21 31 
        ///4e 4c 53 55 
        ///31 2d 5a 75 
        ///6c 65 74 7a 
        ///74 20 67 65 
        ///73 70 69 65 
        ///6c 74 1a 0d 
        ///0a 49 53 43 
        ///50 00 00 00 
        ///10 00 00 00 
        ///1f 01 00 00 
        ///00 21 31 4e 
        ///4c 53 55 32 
        ///2d 5a 75 6c 
        ///65 74 7a 74 
        ///20 68 69 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Umlaute {
            get {
                return ResourceManager.GetString("Umlaute", resourceCulture);
            }
        }
    }
}
